name: Build ZMK firmware

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Manually initialize ZMK submodules
        run: |
          cd config/zmk
          git submodule update --init --recursive

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install west
        run: pip install west

      - name: Initialize west
        run: west init -l config

      - name: Update west
        run: west update

      - name: Export Zephyr
        run: west zephyr-export

      - name: Build left firmware
        run: |
          west build -s config/zmk/app -d build/left -b nice_nano_v2 -- -DSHIELD=tbn_left -DZMK_CONFIG=$(pwd)/config

      - name: Upload left firmware
        uses: actions/upload-artifact@v3
        with:
          name: tbn_left.uf2
          path: build/left/zephyr/zmk.uf2

      - name: Build right firmware
        run: |
          west build -s config/zmk/app -d build/right -b nice_nano_v2 -- -DSHIELD=tbn_right -DZMK_CONFIG=$(pwd)/config

      - name: Upload right firmware
        uses: actions/upload-artifact@v3
        with:
          name: tbn_right.uf2
          path: build/right/zephyr/zmk.uf2
