name: Build Firmware

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_left:
    name: Build Left Half (tbn_left)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: config/zmk/app  # Работаем из папки, где лежит app
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive  # Чтобы подтянуть подмодули, если есть

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install west
        run: pip install west

      - name: Initialize west workspace
        run: west init -l .

      - name: Update west workspace
        run: west update

      - name: Build firmware (left)
        run: west build -s app -d build/left -b nice_nano_v2 -- -DSHIELD=tbn_left

      - name: Upload firmware artifact (left)
        uses: actions/upload-artifact@v4
        with:
          name: firmware-left
          path: build/left/zephyr/zmk.uf2

  build_right:
    name: Build Right Half (tbn_right)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: config/zmk/app
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install west
        run: pip install west

      - name: Initialize west workspace
        run: west init -l .

      - name: Update west workspace
        run: west update

      - name: Build firmware (right)
        run: west build -s app -d build/right -b nice_nano_v2 -- -DSHIELD=tbn_right

      - name: Upload firmware artifact (right)
        uses: actions/upload-artifact@v4
        with:
          name: firmware-right
          path: build/right/zephyr/zmk.uf2
